language: python
python: '2.7'
sudo: required
services:
- docker
notifications:
  email:
    recipients:
    - tgu@anl.gov
    on_success: never
    on_failure: always
branches:
  only:
  - master
before_install:
- docker version
- python --version
- javac -version
- java -version
install:
- pip install coveralls
- git clone https://github.com/kbase/jars
- git clone https://github.com/kbase/kb_sdk
- cd kb_sdk
- make
- export PATH=$(pwd)/bin:$PATH
- cd ../
script:
- kb-sdk validate
